import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React from 'react'
import dynamic from 'next/dynamic'

const OnfidoComp = dynamic(() => import('../components/Onfido'), {
  ssr: false,
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Onfido</h1>
        <OnfidoComp/>
      </main>
    </>
  )
}
